Руководство по сборке функции, написанной на Typescript под Yandex Cl…
yandex-cloud/docs pull request #339
Opened 2022-05-18 14:33 UTC by vladd11

…oud Functions.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.
Payment account id: dn234cpco8euvucuv17s

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Description of changes:

2022-05-18 17:01 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-fa1598e0-d6ca-11ec-8317-76645f114f8a/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-fa1598e0-d6ca-11ec-8317-76645f114f8a/en/index.html).

2022-05-18 17:34 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-69a5a340-d6cf-11ec-9318-f907000724da/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-69a5a340-d6cf-11ec-9318-f907000724da/en/index.html).

2022-05-18 17:49 UTC, yfm-team commented
Есть критические ошибки, собрать документацию невозможно. Исправьте их и повторите попытку.

:x:  Link is unreachable: ../_includes/name-format.md in /en/functions/tutorials/nodejs-typescript.md
:x:  Skip error: Error: ENOENT: no such file or directory, open '/en/functions/_includes/name-format.md' in /en/functions/_includes/name-format.md

2022-05-20 14:31 UTC, DavyJohnes requested changes
Прошу прощения за длительное ожидание

2022-05-20 14:31 UTC, DavyJohnes commented on en/functions/tutorials/nodejs-typescript.md
> +npm install esbuild --save-dev
Давайте тут опишем только про `tsc`, без использования `esbuild`? Эта штука не то чтобы прям must have для работы с typescript проектом в serverless функции, к тому же есть альтернативы, которые могут в зависимости от поставленных задач или вообще из соображений вкуса.

2022-05-20 14:31 UTC, DavyJohnes commented on en/functions/tutorials/nodejs-typescript.md
> +- Create (or append) [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file:
На самом деле тут будет правильным сделать `ts --init`, тогда конкретное содержимое `tsconfig.json` можно не приводить.

2022-05-20 14:31 UTC, DavyJohnes commented on en/functions/tutorials/nodejs-typescript.md
> +- Management console
Здесь наверное можно просто вставить ссылку на имеющийся гайд по загрузке функции из zip архива? Типа [вот этого](https://cloud.yandex.com/en-ru/docs/functions/operations/function/version-manage#zip-archive).

2022-05-20 17:14 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-93f18580-d85d-11ec-8534-6da1f3ce14ec/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-93f18580-d85d-11ec-8534-6da1f3ce14ec/en/index.html).

2022-05-20 17:15 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-0c1f5c30-d85e-11ec-9288-e801cc70636e/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-0c1f5c30-d85e-11ec-9288-e801cc70636e/en/index.html).

2022-05-20 17:21 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-d2a77cc0-d85e-11ec-818d-9895d43f9cd4/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-d2a77cc0-d85e-11ec-818d-9895d43f9cd4/en/index.html).

2022-05-20 17:22 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-1ff40020-d85f-11ec-9138-7a7b66772bf3/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-1ff40020-d85f-11ec-9138-7a7b66772bf3/en/index.html).

2022-05-23 07:15 UTC, DavyJohnes commented on en/functions/tutorials/nodejs-typescript.md
> +npx ts --init --preserveConstEnums --moduleResolution Node --isolatedModules --outDir build --strict false --target ES2019
При прочих равных мы рекомендуем использовать последнюю из доступных версий nodejs, то есть 16 в данном случае. Раз так, то давайте рекомендовать сразу компилировать в `ES2021`?

2022-05-23 10:46 UTC, vladd11 commented
Исправлено. Изначально в этом руководстве предполагалось, что если пользователь хочет перенести JS функцию на TypeScript => у него может быть любой runtime => ES2019 самая совместимая версия. Если у него готовый проект, он выберет максимальную версию сам.

2022-05-23 10:47 UTC, DavyJohnes commented
lgtm. Жду инструкцию на русском и approve.

2022-05-23 10:51 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-f7961870-da84-11ec-8319-7856228100ef/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-f7961870-da84-11ec-8319-7856228100ef/en/index.html).

2022-05-23 11:05 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-19c1bc90-da87-11ec-94b5-0c1f38835b22/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-19c1bc90-da87-11ec-94b5-0c1f38835b22/en/index.html).

2022-05-23 11:07 UTC, DavyJohnes approved these changes

2022-05-23 11:17 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-0f0f64f0-da87-11ec-9ac3-ca26ad95f12e/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-0f0f64f0-da87-11ec-9ac3-ca26ad95f12e/en/index.html).

2022-05-23 11:18 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-325145f0-da87-11ec-969a-4864c5fda854/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-325145f0-da87-11ec-969a-4864c5fda854/en/index.html).

2022-05-23 11:35 UTC, vladd11 commented
Исправил несоответствие title в toc.yml
![OnPaste 20220523-153231](https://user-images.githubusercontent.com/27568333/169810262-86d87a60-8f86-484d-8efd-4e31502e3f00.png)

2022-05-23 11:44 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-4ece6af0-da8c-11ec-846b-137cd1a0f42f/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-4ece6af0-da8c-11ec-846b-137cd1a0f42f/en/index.html).

2022-05-26 11:41 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-b2f1b810-dce5-11ec-8e8d-1a97f1189fff/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-b2f1b810-dce5-11ec-8e8d-1a97f1189fff/en/index.html).

2022-05-26 11:42 UTC, yfm-team commented
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-c8a8a600-dce5-11ec-8f86-0c35340074cf/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-c8a8a600-dce5-11ec-8f86-0c35340074cf/en/index.html).

2022-05-26 12:00 UTC, merged

2022-05-27 07:04 UTC, myusosnovskay commented
Выдали грант.